#! /usr/bin/env bash
#set -uvx
set -e
cd "$(dirname "$0")"
cwd=`pwd`
ts=`date "+%Y.%m%d.%H%M.%S"`

dos2unix pkg-list.txt 1>&2

while read -r pkg; do
  echo Checking: $pkg 1>&2
  while read -r release; do
    if [[ ! -z "$release" ]]; then
      echo list-older: $release 1>&2
      echo $release
     fi
   done <<< $(git-release-older $pkg)
done <<< "$(cat pkg-list.txt)"
