#! /usr/bin/env bash
#set -uvx
set -e
cd "$(dirname "$0")"
cwd=`pwd`
ts=`date "+%Y.%m%d.%H%M.%S"`

while read -r release; do
  echo "\$release: $release"
  git-release-remove $release
done <<< "$(./list-older)"
