#! /usr/bin/env bash
#set -uvx
set -e
cd "$(dirname "$0")"
cwd=`pwd`
ts=`date "+%Y.%m%d.%H%M.%S"`

while read -r pkg; do
  echo $pkg
  while read -r release; do
    echo $release
  done <<< $(git-release-older $pkg)
done <<< "$(cat pkg-list.txt)"
